export const SIGNUP_COUNTRIES = [
  "Pakistan",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Bahrain",
  "Kuwait",
  "Oman",
  "India",
  "Bangladesh",
  "Afghanistan",
  "United Kingdom",
  "United States",
  "Canada",
  "Australia",
  "Malaysia",
  "Singapore",
  "Turkey",
  "Egypt",
  "Jordan",
  "Lebanon",
  "South Africa",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "China",
  "Japan",
  "Other",
] as const
