import { z } from "zod"

export const invoiceTemplateIdSchema = z.enum([
  "classic",
  "minimal",
  "modern",
  "professional",
])

export type InvoiceTemplateId = z.infer<typeof invoiceTemplateIdSchema>

export const INVOICE_TEMPLATE_STORAGE_KEY = "custoray-invoice-template-v1"
export const INVOICE_TEMPLATE_COPY_STORAGE_KEY = "custoray-invoice-template-copy-v1"
export const INVOICE_TEMPLATE_COLORS_STORAGE_KEY = "custoray-invoice-template-colors-v1"

export const invoiceTemplateCopySchema = z.object({
  documentTitle: z.string(),
  billToLabel: z.string(),
  thankYouMessage: z.string(),
  footerNote: z.string(),
})

export type InvoiceTemplateCopy = z.infer<typeof invoiceTemplateCopySchema>

export const DEFAULT_INVOICE_TEMPLATE_COPY: InvoiceTemplateCopy = {
  documentTitle: "Sales Invoice",
  billToLabel: "Bill To",
  thankYouMessage: "Thank you for your business!",
  footerNote: "Generated by Custoray",
}

export type InvoiceTemplateDefinition = {
  id: InvoiceTemplateId
  name: string
  description: string
  accent: string
  accentMuted: string
  headerBg: string
  headerText: string
  tableHeadBg: string
  tableHeadText: string
  fontFamily: string
  showAccentBar: boolean
  billToBg: string
  billToBorder: string
  grandTotalBg: string
  grandTotalText: string
  headerPanel?: boolean
}

export type InvoiceTemplateColorOverrides = Partial<
  Pick<
    InvoiceTemplateDefinition,
    | "accent"
    | "accentMuted"
    | "headerBg"
    | "headerText"
    | "tableHeadBg"
    | "tableHeadText"
    | "billToBg"
    | "billToBorder"
    | "grandTotalBg"
    | "grandTotalText"
  >
>

export const invoiceTemplateColorOverridesSchema = z.object({
  accent: z.string().optional(),
  accentMuted: z.string().optional(),
  headerBg: z.string().optional(),
  headerText: z.string().optional(),
  tableHeadBg: z.string().optional(),
  tableHeadText: z.string().optional(),
  billToBg: z.string().optional(),
  billToBorder: z.string().optional(),
  grandTotalBg: z.string().optional(),
  grandTotalText: z.string().optional(),
})

export type InvoiceTemplateColorOverridesInput = z.infer<
  typeof invoiceTemplateColorOverridesSchema
>

export const INVOICE_COLOR_FIELDS: {
  key: keyof InvoiceTemplateColorOverrides
  label: string
}[] = [
  { key: "accent", label: "Accent" },
  { key: "accentMuted", label: "Accent light" },
  { key: "headerBg", label: "Header background" },
  { key: "headerText", label: "Header text" },
  { key: "tableHeadBg", label: "Table header" },
  { key: "tableHeadText", label: "Table header text" },
  { key: "billToBg", label: "Bill-to panel" },
  { key: "billToBorder", label: "Borders" },
  { key: "grandTotalBg", label: "Total bar" },
  { key: "grandTotalText", label: "Total text" },
]

export const INVOICE_TEMPLATES: InvoiceTemplateDefinition[] = [
  {
    id: "classic",
    name: "Classic",
    description: "Green accent with bold dark totals — the default Custoray look.",
    accent: "#92c720",
    accentMuted: "#ecfccb",
    headerBg: "#ffffff",
    headerText: "#111827",
    tableHeadBg: "#111827",
    tableHeadText: "#ffffff",
    fontFamily: '"Segoe UI", Arial, sans-serif',
    showAccentBar: true,
    headerPanel: false,
    billToBg: "#f9fafb",
    billToBorder: "#e5e7eb",
    grandTotalBg: "#111827",
    grandTotalText: "#ffffff",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean monochrome layout with subtle borders and lots of whitespace.",
    accent: "#374151",
    accentMuted: "#f3f4f6",
    headerBg: "#ffffff",
    headerText: "#111827",
    tableHeadBg: "#f9fafb",
    tableHeadText: "#374151",
    fontFamily: 'Georgia, "Times New Roman", serif',
    showAccentBar: false,
    headerPanel: false,
    billToBg: "#ffffff",
    billToBorder: "#d1d5db",
    grandTotalBg: "#f3f4f6",
    grandTotalText: "#111827",
  },
  {
    id: "modern",
    name: "Modern",
    description: "Teal highlights and soft panels for a contemporary feel.",
    accent: "#0d9488",
    accentMuted: "#ccfbf1",
    headerBg: "#f0fdfa",
    headerText: "#134e4a",
    tableHeadBg: "#0f766e",
    tableHeadText: "#ffffff",
    fontFamily: '"Segoe UI", Arial, sans-serif',
    showAccentBar: true,
    headerPanel: true,
    billToBg: "#ecfeff",
    billToBorder: "#99f6e4",
    grandTotalBg: "#0d9488",
    grandTotalText: "#ffffff",
  },
  {
    id: "professional",
    name: "Professional",
    description: "Navy and gold tones suited for formal B2B invoices.",
    accent: "#c9a227",
    accentMuted: "#fef3c7",
    headerBg: "#1e3a5f",
    headerText: "#ffffff",
    tableHeadBg: "#1e3a5f",
    tableHeadText: "#ffffff",
    fontFamily: '"Segoe UI", Arial, sans-serif',
    showAccentBar: true,
    headerPanel: true,
    billToBg: "#f8fafc",
    billToBorder: "#cbd5e1",
    grandTotalBg: "#1e3a5f",
    grandTotalText: "#ffffff",
  },
]

export function getInvoiceTemplate(id: InvoiceTemplateId): InvoiceTemplateDefinition {
  return INVOICE_TEMPLATES.find((t) => t.id === id) ?? INVOICE_TEMPLATES[0]
}

export function resolveInvoiceTemplate(
  id: InvoiceTemplateId,
  colorOverrides?: InvoiceTemplateColorOverrides
): InvoiceTemplateDefinition {
  const base = getInvoiceTemplate(id)
  return colorOverrides ? { ...base, ...colorOverrides } : base
}

export function getDefaultColorsForTemplate(
  id: InvoiceTemplateId
): InvoiceTemplateColorOverrides {
  const t = getInvoiceTemplate(id)
  return {
    accent: t.accent,
    accentMuted: t.accentMuted,
    headerBg: t.headerBg,
    headerText: t.headerText,
    tableHeadBg: t.tableHeadBg,
    tableHeadText: t.tableHeadText,
    billToBg: t.billToBg,
    billToBorder: t.billToBorder,
    grandTotalBg: t.grandTotalBg,
    grandTotalText: t.grandTotalText,
  }
}

type StoredTemplateColors = Partial<
  Record<InvoiceTemplateId, InvoiceTemplateColorOverrides>
>

function loadAllTemplateColors(): StoredTemplateColors {
  if (typeof window === "undefined") return {}
  const raw = window.localStorage.getItem(INVOICE_TEMPLATE_COLORS_STORAGE_KEY)
  if (!raw) return {}
  try {
    return JSON.parse(raw) as StoredTemplateColors
  } catch {
    return {}
  }
}

export function loadInvoiceTemplateColors(
  id: InvoiceTemplateId
): InvoiceTemplateColorOverrides {
  const stored = loadAllTemplateColors()[id]
  return stored ? { ...getDefaultColorsForTemplate(id), ...stored } : getDefaultColorsForTemplate(id)
}

export function saveInvoiceTemplateColors(
  id: InvoiceTemplateId,
  colors: InvoiceTemplateColorOverrides
): void {
  if (typeof window === "undefined") return
  const all = loadAllTemplateColors()
  all[id] = colors
  window.localStorage.setItem(INVOICE_TEMPLATE_COLORS_STORAGE_KEY, JSON.stringify(all))
}

export function resetInvoiceTemplateColors(id: InvoiceTemplateId): void {
  if (typeof window === "undefined") return
  const all = loadAllTemplateColors()
  delete all[id]
  window.localStorage.setItem(INVOICE_TEMPLATE_COLORS_STORAGE_KEY, JSON.stringify(all))
}

export function loadInvoiceTemplate(): InvoiceTemplateId {
  if (typeof window === "undefined") return "classic"
  const raw = window.localStorage.getItem(INVOICE_TEMPLATE_STORAGE_KEY)
  if (!raw || raw.startsWith("custom:")) return "classic"
  const parsed = invoiceTemplateIdSchema.safeParse(raw)
  return parsed.success ? parsed.data : "classic"
}

export function saveInvoiceTemplate(id: InvoiceTemplateId): void {
  if (typeof window === "undefined") return
  window.localStorage.setItem(INVOICE_TEMPLATE_STORAGE_KEY, id)
}

export function loadInvoiceTemplateCopy(): InvoiceTemplateCopy {
  if (typeof window === "undefined") return DEFAULT_INVOICE_TEMPLATE_COPY
  const raw = window.localStorage.getItem(INVOICE_TEMPLATE_COPY_STORAGE_KEY)
  if (!raw) return DEFAULT_INVOICE_TEMPLATE_COPY
  try {
    const parsed = invoiceTemplateCopySchema.safeParse(JSON.parse(raw))
    return parsed.success ? parsed.data : DEFAULT_INVOICE_TEMPLATE_COPY
  } catch {
    return DEFAULT_INVOICE_TEMPLATE_COPY
  }
}

export function saveInvoiceTemplateCopy(copy: InvoiceTemplateCopy): void {
  if (typeof window === "undefined") return
  window.localStorage.setItem(INVOICE_TEMPLATE_COPY_STORAGE_KEY, JSON.stringify(copy))
}

export const invoiceFieldIdSchema = z.enum([
  "company_logo",
  "company_name",
  "company_tagline",
  "company_address",
  "company_contact",
  "document_title",
  "invoice_number",
  "invoice_date",
  "invoice_id",
  "invoice_status",
  "bill_to",
  "customer_name",
  "customer_notes",
  "line_items",
  "line_row_number",
  "line_description",
  "line_qty",
  "line_unit_price",
  "line_amount",
  "subtotal",
  "paid",
  "balance_due",
  "total",
  "thank_you",
  "footer",
])

export type InvoiceFieldId = z.infer<typeof invoiceFieldIdSchema>

export const INVOICE_MERGE_FIELDS: {
  id: InvoiceFieldId
  label: string
  hint: string
  group: "company" | "invoice" | "customer" | "items" | "totals" | "footer"
}[] = [
  { id: "company_logo", label: "Company logo", hint: "{{company_logo}}", group: "company" },
  { id: "company_name", label: "Company name", hint: "{{company_name}}", group: "company" },
  { id: "company_tagline", label: "Tagline", hint: "{{company_tagline}}", group: "company" },
  { id: "company_address", label: "Address", hint: "{{company_address}}", group: "company" },
  { id: "company_contact", label: "Phone & email", hint: "{{company_contact}}", group: "company" },
  { id: "document_title", label: "Document title", hint: "{{document_title}}", group: "invoice" },
  { id: "invoice_number", label: "Invoice number", hint: "{{invoice_number}}", group: "invoice" },
  { id: "invoice_date", label: "Invoice date", hint: "{{invoice_date}}", group: "invoice" },
  { id: "invoice_id", label: "Internal ID", hint: "{{invoice_id}}", group: "invoice" },
  { id: "invoice_status", label: "Status", hint: "{{invoice_status}}", group: "invoice" },
  { id: "bill_to", label: "Bill to label", hint: "{{bill_to}}", group: "customer" },
  { id: "customer_name", label: "Customer name", hint: "{{customer_name}}", group: "customer" },
  { id: "customer_notes", label: "Customer notes", hint: "{{customer_notes}}", group: "customer" },
  { id: "line_items", label: "Line items table", hint: "{{line_items}}", group: "items" },
  { id: "line_row_number", label: "Row # column", hint: "{{line_row_number}}", group: "items" },
  { id: "line_description", label: "Description column", hint: "{{line_description}}", group: "items" },
  { id: "line_qty", label: "Quantity column", hint: "{{line_qty}}", group: "items" },
  { id: "line_unit_price", label: "Unit price column", hint: "{{line_unit_price}}", group: "items" },
  { id: "line_amount", label: "Amount column", hint: "{{line_amount}}", group: "items" },
  { id: "subtotal", label: "Subtotal", hint: "{{subtotal}}", group: "totals" },
  { id: "paid", label: "Paid amount", hint: "{{paid}}", group: "totals" },
  { id: "balance_due", label: "Balance due", hint: "{{balance_due}}", group: "totals" },
  { id: "total", label: "Grand total", hint: "{{total}}", group: "totals" },
  { id: "thank_you", label: "Thank you message", hint: "{{thank_you}}", group: "footer" },
  { id: "footer", label: "Footer note", hint: "{{footer}}", group: "footer" },
]

export const invoiceBuilderLabelsSchema = z.object({
  documentTitle: z.string(),
  billToLabel: z.string(),
  dateLabel: z.string(),
  invoiceIdLabel: z.string(),
  statusLabel: z.string(),
  rowNumberColumn: z.string(),
  descriptionColumn: z.string(),
  qtyColumn: z.string(),
  rateColumn: z.string(),
  amountColumn: z.string(),
  subtotalLabel: z.string(),
  paidLabel: z.string(),
  balanceLabel: z.string(),
  totalLabel: z.string(),
  thankYouMessage: z.string(),
  footerNote: z.string(),
})

export type InvoiceBuilderLabels = z.infer<typeof invoiceBuilderLabelsSchema>

export const invoiceFieldVisibilitySchema = z.object({
  company_logo: z.boolean(),
  company_name: z.boolean(),
  company_tagline: z.boolean(),
  company_address: z.boolean(),
  company_contact: z.boolean(),
  document_title: z.boolean(),
  invoice_number: z.boolean(),
  invoice_date: z.boolean(),
  invoice_id: z.boolean(),
  invoice_status: z.boolean(),
  bill_to: z.boolean(),
  customer_name: z.boolean(),
  customer_notes: z.boolean(),
  line_items: z.boolean(),
  line_row_number: z.boolean(),
  line_description: z.boolean(),
  line_qty: z.boolean(),
  line_unit_price: z.boolean(),
  line_amount: z.boolean(),
  subtotal: z.boolean(),
  paid: z.boolean(),
  balance_due: z.boolean(),
  total: z.boolean(),
  thank_you: z.boolean(),
  footer: z.boolean(),
})

export const invoiceBuilderConfigSchema = z.object({
  fields: invoiceFieldVisibilitySchema,
  labels: invoiceBuilderLabelsSchema,
  companyNameOverride: z.string(),
  companyTaglineOverride: z.string(),
  companyAddressOverride: z.string(),
  companyContactOverride: z.string(),
  logoUrlOverride: z.string(),
})

export type InvoiceBuilderConfig = z.infer<typeof invoiceBuilderConfigSchema>

export function normalizeInvoiceBuilderConfig(
  config: Partial<InvoiceBuilderConfig> & {
    fields?: Partial<Record<InvoiceFieldId, boolean>>
    labels?: Partial<InvoiceBuilderLabels>
  }
): InvoiceBuilderConfig {
  const defaults = defaultInvoiceBuilderConfig()
  return {
    ...defaults,
    ...config,
    fields: { ...defaults.fields, ...config.fields },
    labels: { ...defaults.labels, ...config.labels },
    companyNameOverride: config.companyNameOverride ?? defaults.companyNameOverride,
    companyTaglineOverride: config.companyTaglineOverride ?? defaults.companyTaglineOverride,
    companyAddressOverride: config.companyAddressOverride ?? defaults.companyAddressOverride,
    companyContactOverride: config.companyContactOverride ?? defaults.companyContactOverride,
    logoUrlOverride: config.logoUrlOverride ?? defaults.logoUrlOverride,
  }
}

export const customInvoiceTemplateSchema = z.object({
  id: z.string(),
  name: z.string(),
  baseLayout: invoiceTemplateIdSchema,
  colors: invoiceTemplateColorOverridesSchema,
  builder: invoiceBuilderConfigSchema,
  createdAt: z.string(),
})

export type CustomInvoiceTemplate = z.infer<typeof customInvoiceTemplateSchema>

export function defaultInvoiceBuilderFields(): Record<InvoiceFieldId, boolean> {
  return {
    company_logo: true,
    company_name: true,
    company_tagline: true,
    company_address: true,
    company_contact: true,
    document_title: true,
    invoice_number: true,
    invoice_date: true,
    invoice_id: true,
    invoice_status: true,
    bill_to: true,
    customer_name: true,
    customer_notes: true,
    line_items: true,
    line_row_number: false,
    line_description: true,
    line_qty: true,
    line_unit_price: true,
    line_amount: true,
    subtotal: true,
    paid: true,
    balance_due: true,
    total: true,
    thank_you: true,
    footer: true,
  }
}

export function defaultInvoiceBuilderLabels(): InvoiceBuilderLabels {
  return {
    documentTitle: "Sales Invoice",
    billToLabel: "Bill To",
    dateLabel: "Date",
    invoiceIdLabel: "Invoice ID",
    statusLabel: "Status",
    rowNumberColumn: "#",
    descriptionColumn: "Description",
    qtyColumn: "Qty",
    rateColumn: "Unit Price",
    amountColumn: "Amount",
    subtotalLabel: "Subtotal",
    paidLabel: "Paid",
    balanceLabel: "Balance Due",
    totalLabel: "Total",
    thankYouMessage: "Thank you for your business!",
    footerNote: "Generated by Custoray",
  }
}

export function defaultInvoiceBuilderConfig(): InvoiceBuilderConfig {
  return {
    fields: defaultInvoiceBuilderFields(),
    labels: defaultInvoiceBuilderLabels(),
    companyNameOverride: "",
    companyTaglineOverride: "",
    companyAddressOverride: "",
    companyContactOverride: "",
    logoUrlOverride: "",
  }
}

/** Preset layouts are read-only — always use factory defaults for display and PDF. */
export function resolvePresetTemplate(id: InvoiceTemplateId): {
  template: InvoiceTemplateDefinition
  colors: InvoiceTemplateColorOverrides
  builder: InvoiceBuilderConfig
} {
  return {
    template: getInvoiceTemplate(id),
    colors: getDefaultColorsForTemplate(id),
    builder: defaultInvoiceBuilderConfig(),
  }
}

export function draftFromPreset(id: InvoiceTemplateId): {
  baseLayout: InvoiceTemplateId
  colors: InvoiceTemplateColorOverrides
  builder: InvoiceBuilderConfig
  suggestedName: string
} {
  const meta = getInvoiceTemplate(id)
  return {
    baseLayout: id,
    colors: getDefaultColorsForTemplate(id),
    builder: defaultInvoiceBuilderConfig(),
    suggestedName: `My ${meta.name} template`,
  }
}

export function builderConfigToCopy(config: InvoiceBuilderConfig): InvoiceTemplateCopy {
  return {
    documentTitle: config.labels.documentTitle,
    billToLabel: config.labels.billToLabel,
    thankYouMessage: config.labels.thankYouMessage,
    footerNote: config.labels.footerNote,
  }
}

export function copyToBuilderLabels(
  copy: InvoiceTemplateCopy,
  labels: InvoiceBuilderLabels = defaultInvoiceBuilderLabels()
): InvoiceBuilderLabels {
  return {
    ...labels,
    documentTitle: copy.documentTitle,
    billToLabel: copy.billToLabel,
    thankYouMessage: copy.thankYouMessage,
    footerNote: copy.footerNote,
  }
}

const INVOICE_BUILDER_STORAGE_KEY = "custoray-invoice-builder-v1"
const INVOICE_CUSTOM_TEMPLATES_KEY = "custoray-invoice-custom-templates-v1"

export function loadInvoiceBuilderConfig(): InvoiceBuilderConfig {
  if (typeof window === "undefined") return defaultInvoiceBuilderConfig()
  try {
    const raw = window.localStorage.getItem(INVOICE_BUILDER_STORAGE_KEY)
    if (!raw) {
      const legacy = loadInvoiceTemplateCopy()
      return {
        ...defaultInvoiceBuilderConfig(),
        labels: copyToBuilderLabels(legacy),
      }
    }
    const parsed = invoiceBuilderConfigSchema.safeParse(JSON.parse(raw))
    return parsed.success
      ? normalizeInvoiceBuilderConfig(parsed.data)
      : normalizeInvoiceBuilderConfig(JSON.parse(raw) as Partial<InvoiceBuilderConfig>)
  } catch {
    return defaultInvoiceBuilderConfig()
  }
}

export function saveInvoiceBuilderConfig(config: InvoiceBuilderConfig): void {
  if (typeof window === "undefined") return
  window.localStorage.setItem(INVOICE_BUILDER_STORAGE_KEY, JSON.stringify(config))
  saveInvoiceTemplateCopy(builderConfigToCopy(config))
}

export function loadCustomInvoiceTemplates(): CustomInvoiceTemplate[] {
  if (typeof window === "undefined") return []
  try {
    const raw = window.localStorage.getItem(INVOICE_CUSTOM_TEMPLATES_KEY)
    if (!raw) return []
    const parsed = z.array(customInvoiceTemplateSchema).safeParse(JSON.parse(raw))
    if (parsed.success) return parsed.data
    const loose = JSON.parse(raw) as CustomInvoiceTemplate[]
    if (!Array.isArray(loose)) return []
    return loose.map((t) => ({
      ...t,
      builder: normalizeInvoiceBuilderConfig(t.builder),
    }))
  } catch {
    return []
  }
}

export function saveCustomInvoiceTemplates(templates: CustomInvoiceTemplate[]): void {
  if (typeof window === "undefined") return
  window.localStorage.setItem(INVOICE_CUSTOM_TEMPLATES_KEY, JSON.stringify(templates))
}

export function createCustomInvoiceTemplate(
  name: string,
  baseLayout: InvoiceTemplateId,
  colors: InvoiceTemplateColorOverrides,
  builder: InvoiceBuilderConfig
): CustomInvoiceTemplate {
  return {
    id: `custom-${Date.now()}`,
    name,
    baseLayout,
    colors,
    builder,
    createdAt: new Date().toISOString(),
  }
}

export type ActiveInvoiceTemplateRef =
  | { kind: "preset"; id: InvoiceTemplateId }
  | { kind: "custom"; id: string }

export function loadActiveInvoiceTemplateRef(): ActiveInvoiceTemplateRef {
  if (typeof window === "undefined") return { kind: "preset", id: "classic" }
  const raw = window.localStorage.getItem(INVOICE_TEMPLATE_STORAGE_KEY)
  if (raw?.startsWith("custom:")) {
    return { kind: "custom", id: raw.slice("custom:".length) }
  }
  const parsed = invoiceTemplateIdSchema.safeParse(raw)
  return { kind: "preset", id: parsed.success ? parsed.data : "classic" }
}

export function saveActiveInvoiceTemplateRef(ref: ActiveInvoiceTemplateRef): void {
  if (typeof window === "undefined") return
  if (ref.kind === "custom") {
    window.localStorage.setItem(INVOICE_TEMPLATE_STORAGE_KEY, `custom:${ref.id}`)
  } else {
    window.localStorage.setItem(INVOICE_TEMPLATE_STORAGE_KEY, ref.id)
  }
}

export function resolveActiveTemplateForPdf(): {
  templateId: InvoiceTemplateId
  colors: InvoiceTemplateColorOverrides
  builder: InvoiceBuilderConfig
} {
  const ref = loadActiveInvoiceTemplateRef()
  if (ref.kind === "custom") {
    const custom = loadCustomInvoiceTemplates().find((t) => t.id === ref.id)
    if (custom) {
      return {
        templateId: custom.baseLayout,
        colors: custom.colors,
        builder: custom.builder,
      }
    }
  }
  const presetId = ref.kind === "preset" ? ref.id : "classic"
  const preset = resolvePresetTemplate(presetId)
  return {
    templateId: presetId,
    colors: preset.colors,
    builder: preset.builder,
  }
}

export const SAMPLE_INVOICE_PREVIEW = {
  invoiceNumber: "INV-1001",
  customerName: "Acme Retail Co.",
  orderDate: "2026-06-01",
  totalAmount: "45,200.00",
  paidAmount: "45,200.00",
  companyName: "Custoray",
  companyTagline: "Inventory & Sales Management",
  companyAddress: "123 Business Park, Suite 400",
  companyContact: "+92 300 1234567 · billing@custoray.com",
  customerNotes: "Deliver before 5 PM",
  lines: [
    { productName: "Premium Basmati Rice 25kg", quantity: 8, unitPrice: "3,200.00", lineTotal: "25,600.00" },
    { productName: "Sunflower Oil 5L", quantity: 12, unitPrice: "1,100.00", lineTotal: "13,200.00" },
    { productName: "Mixed Spices Carton", quantity: 4, unitPrice: "1,600.00", lineTotal: "6,400.00" },
    { productName: "Delivery charge", quantity: 1, unitPrice: "0.00", lineTotal: "0.00" },
  ],
}
